/**
 * k6/load-tests/load-test.js — Ramp Load Test (HPA Validation)
 * ─────────────────────────────────────────────────────────────────────────────
 * PURPOSE: Validate HPA (HorizontalPodAutoscaler) scales correctly under load.
 * Gradually ramps from 0 to 50 concurrent users, holds, then ramps down.
 *
 * WHAT THIS TESTS:
 *   1. HPA triggers: backend pods scale from 2 → 5 at ~70% CPU threshold
 *   2. Scale-up latency: how long until new pods are Ready and serving traffic
 *   3. Throughput: how many req/s the cluster sustains under load
 *   4. Response times: do they degrade gracefully under load?
 *   5. Scale-down: pods reduce after load drops (Cluster Autoscaler too)
 *
 * EXPECTED HPA BEHAVIOR:
 *   VUs:   0  →  10  →  30  →  50  →  50  →  50  →  30  →  10  →  0
 *   Pods:  2  →   2  →   3  →   5  →   5  →   5  →   3  →   2  →  2
 *   Time: 0s  → 2m  →  4m  →  6m  →  8m  → 10m  → 12m  → 14m  → 16m
 *
 * MONITORING DURING TEST (separate terminal):
 *   watch -n 5 'kubectl get hpa,pods -n three-tier'
 *   kubectl top pods -n three-tier --containers
 *
 * RUN COMMAND:
 *   k6 run k6/load-tests/load-test.js \
 *     -e BASE_URL=http://<ALB-DNS> \
 *     --out json=results/load-test-$(date +%Y%m%d-%H%M).json
 * ─────────────────────────────────────────────────────────────────────────────
 */

import http from "k6/http";
import { check, sleep } from "k6";
import { Counter, Rate, Trend, Gauge } from "k6/metrics";

// ─────────────────────────────────────────────────────────────────────────────
// CUSTOM METRICS
// ─────────────────────────────────────────────────────────────────────────────
const successfulRequests = new Counter("successful_requests");
const errorRate = new Rate("error_rate");
const apiLatencyTrend = new Trend("api_latency_ms", true); // true = percentiles
const writeLatency = new Trend("write_latency_ms", true);

// ─────────────────────────────────────────────────────────────────────────────
// TEST CONFIGURATION — RAMPING STAGES
// ─────────────────────────────────────────────────────────────────────────────
export const options = {
  // Stages define the VU ramp pattern
  stages: [
    { duration: "2m", target: 10 },  // Ramp up to 10 VUs (warm up)
    { duration: "2m", target: 30 },  // Ramp up to 30 VUs (medium load)
    { duration: "2m", target: 50 },  // Ramp up to 50 VUs (peak load)
    { duration: "4m", target: 50 },  // Hold at 50 VUs (observe HPA scale-up)
    { duration: "2m", target: 30 },  // Ramp down to 30 VUs
    { duration: "2m", target: 10 },  // Ramp down to 10 VUs
    { duration: "2m", target: 0 },   // Ramp down to 0 (observe HPA scale-down)
  ],
  // Total duration: 16 minutes

  // Thresholds — what "passing" means for this load test
  thresholds: {
    // 95% of all requests < 1 second (more lenient than smoke test due to load)
    http_req_duration: ["p(95)<1000", "p(99)<2000"],

    // Error rate < 5% under load (some errors expected at peak)
    http_req_failed: ["rate<0.05"],

    // Our custom metrics
    api_latency_ms: ["p(95)<800"],
    write_latency_ms: ["p(95)<1200"],
    error_rate: ["rate<0.05"],
  },
};

const BASE_URL = __ENV.BASE_URL || "http://localhost:3000";
const HEADERS = {
  "Content-Type": "application/json",
  Accept: "application/json",
};

// ─────────────────────────────────────────────────────────────────────────────
// LOAD SCENARIO
// ─────────────────────────────────────────────────────────────────────────────
export default function () {
  const scenarioWeight = Math.random();
  // Simulate realistic traffic distribution:
  //   70% reads (GET /api/tasks) — typical for a todo app
  //   20% writes (POST /api/tasks) — task creation
  //   10% health checks

  if (scenarioWeight < 0.7) {
    // READ PATH: List all tasks
    const start = Date.now();
    const res = http.get(`${BASE_URL}/api/tasks`, { headers: HEADERS });
    apiLatencyTrend.add(Date.now() - start);

    const ok = check(res, {
      "GET tasks: status 200": (r) => r.status === 200,
      "GET tasks: is array": (r) => {
        try {
          return Array.isArray(JSON.parse(r.body));
        } catch {
          return false;
        }
      },
    });

    if (ok) successfulRequests.add(1);
    errorRate.add(!ok);
    sleep(1 + Math.random() * 2); // Think time: 1-3 seconds between requests
  } else if (scenarioWeight < 0.9) {
    // WRITE PATH: Create a task
    const start = Date.now();
    const payload = JSON.stringify({
      title: `Load Test Task ${__VU}-${__ITER}`,
      // __VU = virtual user number, __ITER = iteration count
      description: `Generated by VU ${__VU} at ${new Date().toISOString()}`,
      completed: false,
    });

    const res = http.post(`${BASE_URL}/api/tasks`, payload, {
      headers: HEADERS,
    });
    writeLatency.add(Date.now() - start);

    const ok = check(res, {
      "POST task: status 201": (r) => r.status === 201,
      "POST task: has id": (r) => {
        try {
          const body = JSON.parse(r.body);
          return body._id || body.id;
        } catch {
          return false;
        }
      },
    });

    if (ok) successfulRequests.add(1);
    errorRate.add(!ok);
    sleep(2 + Math.random() * 3);
  } else {
    // HEALTH CHECK PATH
    const res = http.get(`${BASE_URL}/api/health`, { headers: HEADERS });
    check(res, { "health: status 200": (r) => r.status === 200 });
    sleep(0.5);
  }
}

export function setup() {
  console.log(`
╔══════════════════════════════════════════════════════════╗
║                    LOAD TEST STARTING                    ║
║                                                          ║
║  Target:   ${BASE_URL.padEnd(45)}║
║  Duration: 16 minutes                                    ║
║  Peak VUs: 50                                            ║
║                                                          ║
║  Monitor HPA with:                                       ║
║    watch -n 5 'kubectl get hpa,pods -n three-tier'      ║
╚══════════════════════════════════════════════════════════╝
  `);
}
