/**
 * models/task.js — Mongoose Data Model (Schema + Model)
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHAT THIS FILE DOES
 * ═══════════════════════════════════════════════════════════════════════════
 * Defines the data structure (schema) for a "Task" document in MongoDB,
 * then compiles it into a Mongoose Model.
 *
 * The Model is what routes/tasks.js uses to perform CRUD operations.
 * It provides methods like: Task.find(), Task.findById(), task.save(),
 * Task.findByIdAndUpdate(), Task.findByIdAndDelete()
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * MONGOOSE vs MONGODB DRIVER — WHY MONGOOSE?
 * ═══════════════════════════════════════════════════════════════════════════
 * Raw MongoDB driver (mongodb npm package):
 *   - Low-level, full control
 *   - No schema enforcement — any JSON shape can be inserted
 *   - No built-in validation
 *
 * Mongoose (ODM — Object Document Mapper):
 *   + Schema validation (type checking, required fields)
 *   + Automatic timestamps (createdAt, updatedAt)
 *   + Middleware hooks (pre/post save, validate, delete)
 *   + Virtual fields and custom methods
 *   + Query building API (.find(), .populate(), .lean(), etc.)
 *
 * For this CRUD application, Mongoose is the right choice. The schema
 * guarantees that every Task document in MongoDB has the correct shape.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * MONGODB DOCUMENT STRUCTURE (what gets stored in the DB)
 * ═══════════════════════════════════════════════════════════════════════════
 * {
 *   "_id":       ObjectId("64a3f1b2c0e7891234567890"),  ← Auto-generated by MongoDB
 *   "task":      "Set up EKS with Terraform",           ← Our field (string)
 *   "completed": false,                                  ← Our field (boolean)
 *   "createdAt": ISODate("2026-05-25T14:00:00.000Z"),   ← Auto by timestamps: true
 *   "updatedAt": ISODate("2026-05-25T14:00:00.000Z"),   ← Auto by timestamps: true
 *   "__v":       0                                       ← Mongoose version key
 * }
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * KUBERNETES STORAGE CONTEXT
 * ═══════════════════════════════════════════════════════════════════════════
 * These documents are stored in MongoDB's data directory (/data/db).
 * In K8s, this directory is backed by an EBS PersistentVolume (gp2, 5Gi).
 *
 * If the MongoDB pod is deleted and recreated:
 *   ✅ PersistentVolume remains (data persists)
 *   ✅ New pod mounts the same EBS volume
 *   ✅ All Task documents survive the pod restart
 *
 * If the EBS volume is deleted:
 *   ❌ All documents are lost — this is why backup strategy (Day 28) matters
 */

"use strict";

const mongoose = require("mongoose");

// Schema is the blueprint — defines field names, types, and validation rules
const Schema = mongoose.Schema;

// ─────────────────────────────────────────────────────────────────────────────
// TASK SCHEMA DEFINITION
// ─────────────────────────────────────────────────────────────────────────────
const taskSchema = new Schema(
  {
    /**
     * task — The task description/title
     *
     * type: String      → Only string values accepted (Mongoose validates this)
     * required: true    → Document save() will fail if this field is missing
     *                     Returns a ValidationError with a clear message
     * trim: true        → Removes leading/trailing whitespace before saving
     *                     Prevents storing "  Buy groceries  " when "Buy groceries" intended
     * minlength: 1      → Prevents storing empty strings that pass the `required` check
     * maxlength: 500    → Reasonable limit — prevents abuse / DB bloat
     *
     * NOTE: The frontend sends this as "title" in the POST body but the
     * MongoDB field is named "task". The route handler maps this.
     * In production, aligning naming (always "title") would be cleaner.
     */
    task: {
      type: String,
      required: [true, "Task description is required"],
      trim: true,
      minlength: [1, "Task cannot be empty"],
      maxlength: [500, "Task cannot exceed 500 characters"],
    },

    /**
     * completed — Tracks whether the task is done
     *
     * type: Boolean     → Only true/false accepted
     * default: false    → New tasks start as incomplete (not required in POST body)
     *
     * The frontend sends PUT requests to toggle this field.
     * The checkbox in App.js is bound to this value.
     */
    completed: {
      type: Boolean,
      default: false,
    },
  },
  {
    /**
     * Schema Options
     *
     * timestamps: true
     * Mongoose automatically adds and manages:
     *   - createdAt: Date  → Set when document is first saved
     *   - updatedAt: Date  → Updated on every save/findByIdAndUpdate call
     *
     * This is MUCH better than manually managing these fields.
     * These timestamps are useful for:
     *   - Sorting tasks by creation time
     *   - Auditing when tasks were completed
     *   - Time-based data analysis in Grafana dashboards
     */
    timestamps: true,

    /**
     * versionKey: false
     * By default, Mongoose adds a __v field (version key) to track document
     * versions for optimistic concurrency control.
     * For this simple CRUD app, we disable it to keep documents clean.
     * For apps with concurrent updates, keep it enabled.
     */
    versionKey: false,
  }
);

// ─────────────────────────────────────────────────────────────────────────────
// INDEXES (Production optimization)
// ─────────────────────────────────────────────────────────────────────────────
/**
 * For larger datasets, add indexes to speed up common queries.
 * Example: Finding all incomplete tasks sorted by creation time.
 *
 * taskSchema.index({ completed: 1, createdAt: -1 });
 *
 * In K8s with EBS storage, index creation runs automatically when
 * the backend starts and connects to MongoDB.
 *
 * For this portfolio project, the default _id index is sufficient
 * since we always query by ID for update/delete operations.
 */

// ─────────────────────────────────────────────────────────────────────────────
// COMPILE SCHEMA INTO MODEL
// ─────────────────────────────────────────────────────────────────────────────
/**
 * mongoose.model("Task", taskSchema)
 *
 * Arguments:
 *   "Task"      → Model name (used internally by Mongoose)
 *   taskSchema  → The schema blueprint defined above
 *
 * What this creates:
 *   - A JavaScript class (Model) with built-in CRUD methods
 *   - Mongoose automatically creates/uses a MongoDB collection named "tasks"
 *     (lowercased + pluralized version of "Task")
 *
 * The collection name will be: tasks
 * Full MongoDB path: mongodb://..../tasksdb.tasks
 *                                  └──────┘ └─────┘
 *                                  Database  Collection
 *
 * Usage in routes/tasks.js:
 *   const Task = require("../models/task");
 *   const allTasks = await Task.find({});
 *   const newTask  = await new Task({ task: "...", completed: false }).save();
 */
const Task = mongoose.model("Task", taskSchema);

module.exports = Task;
