/**
 * Tasks.js — Business Logic / Data Layer Component (Controller-like)
 *
 * WHAT THIS FILE DOES:
 * --------------------
 * Tasks is a React Class Component that acts as the "controller" in this app.
 * It holds ALL the state and ALL the event handler logic for CRUD operations.
 * App.js extends this class to inherit all its methods — a pattern using
 * class inheritance instead of hooks or context.
 *
 * ARCHITECTURE PATTERN: Class-Based Component with Inheritance
 * -----------------------------------------------------------
 * Tasks (parent)          → holds state + CRUD handlers
 *   └── App (child)       → extends Tasks, holds the render() / UI
 *
 * This is an older React pattern (pre-hooks). In modern React, you'd use:
 * - Custom hooks (useTaskManager) to replace class methods
 * - Context API or Redux for shared state
 * - Functional components instead of class components
 *
 * WHY IMPORTANT FOR K8S/DEVOPS:
 * ------------------------------
 * Every API call in this file goes through taskServices.js which reads
 * REACT_APP_BACKEND_URL from the environment. In Kubernetes, this value
 * comes from a ConfigMap mounted as an environment variable during the
 * `npm run build` stage inside the Docker image build.
 *
 * STATE SHAPE:
 * {
 *   tasks: Array<Task>   — All tasks fetched from the backend/MongoDB
 *   currentTask: string  — Current value of the input text field (controlled input)
 * }
 *
 * TASK OBJECT SHAPE (from MongoDB via Express API):
 * {
 *   _id:       string   — MongoDB ObjectId (e.g., "64a3f1...")
 *   title:     string   — Task description
 *   completed: boolean  — Whether the task is done
 *   createdAt: Date     — Auto-generated by Mongoose timestamp
 *   updatedAt: Date     — Auto-updated by Mongoose on PUT
 * }
 */

import { Component } from "react";
import {
  addTask,
  getTasks,
  updateTask,
  deleteTask,
} from "./services/taskServices";

class Tasks extends Component {
  // ─────────────────────────────────────────────────────────────────────────
  // INITIAL STATE
  // ─────────────────────────────────────────────────────────────────────────
  // React class component state must be initialized as a class property or
  // in the constructor. Here we use class property syntax (Babel transform).
  // 'tasks' will be populated from the backend. 'currentTask' tracks the
  // text input value (controlled component pattern).
  state = { tasks: [], currentTask: "" };

  // ─────────────────────────────────────────────────────────────────────────
  // LIFECYCLE: componentDidMount
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * componentDidMount() runs ONCE after the component first renders to the DOM.
   * This is the correct place to fetch data from an API in class components.
   *
   * WHY NOT in the constructor? The DOM isn't ready yet. Fetch in mount.
   * WHY NOT in render()? render() runs on every state change — you'd re-fetch infinitely.
   *
   * Kubernetes relevance: If REACT_APP_BACKEND_URL is misconfigured in the
   * ConfigMap, this is where the first failure occurs (CORS error or network error).
   */
  async componentDidMount() {
    try {
      // getTasks() calls GET {REACT_APP_BACKEND_URL}
      // The response shape: { data: [...tasks] }
      const { data } = await getTasks();

      // Update component state with fetched tasks → triggers re-render
      this.setState({ tasks: data });
    } catch (error) {
      // In production, replace with proper error state + user-facing message
      console.log(error);
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // EVENT HANDLER: handleChange
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Controlled input pattern — every keystroke in the TextField updates state.
   * React re-renders on each keystroke, keeping the input in sync with state.
   *
   * Arrow function syntax (=>) auto-binds 'this' — avoids .bind(this) in constructor.
   *
   * @param {Object} event - Synthetic React event object
   * @param {Object} event.currentTarget - The DOM element that fired the event
   * @param {string} event.currentTarget.input - The input element's current value
   */
  handleChange = ({ currentTarget: input }) => {
    this.setState({ currentTask: input.value });
  };

  // ─────────────────────────────────────────────────────────────────────────
  // EVENT HANDLER: handleSubmit
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Called when the form is submitted (Enter key or Submit button click).
   * Creates a new task via the backend API and updates local state optimistically.
   *
   * FLOW:
   *   1. Prevent default form submit (page refresh)
   *   2. Guard: do nothing if input is empty
   *   3. POST to backend → MongoDB stores the new task
   *   4. Append the returned task to local state (no need to re-fetch all tasks)
   *   5. Clear the input field
   *
   * @param {Event} event - The form submit event
   */
  handleSubmit = async (event) => {
    event.preventDefault(); // Prevent HTML form's default page-reload behavior

    // Guard: don't submit empty tasks
    if (this.state.currentTask === "") return;

    try {
      // POST request: { title: currentTask }
      // Backend creates: { _id, title, completed: false, createdAt, updatedAt }
      const { data: task } = await addTask({ title: this.state.currentTask });

      // Optimistic update: append new task to existing list without full re-fetch
      // This gives instant UI feedback without waiting for a full getTasks() call
      const updatedTasks = [...this.state.tasks, task];

      this.setState({ tasks: updatedTasks, currentTask: "" });
    } catch (error) {
      console.log(error);
    }
  };

  // ─────────────────────────────────────────────────────────────────────────
  // EVENT HANDLER: handleUpdate
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Toggles the 'completed' status of a task when its checkbox is clicked.
   *
   * FLOW:
   *   1. Find the task in local state by _id
   *   2. Send PUT request with toggled 'completed' value
   *   3. Replace the task in local state with the updated version from server
   *
   * WHY use server response instead of local toggle?
   * The server is the source of truth. It may apply business rules
   * (e.g., timestamps, validation) before returning the updated task.
   *
   * @param {string} taskId - MongoDB ObjectId of the task to toggle
   */
  handleUpdate = async (taskId) => {
    try {
      // Find current task object in state array
      const index = this.state.tasks.findIndex((task) => task._id === taskId);
      const task = this.state.tasks[index];

      // Toggle the completed boolean
      task.completed = !task.completed;

      // PUT request: sends the entire updated task object
      await updateTask(taskId, task);

      // Replace old task with updated task in state (immutable update)
      const updatedTasks = [...this.state.tasks];
      updatedTasks[index] = task;
      this.setState({ tasks: updatedTasks });
    } catch (error) {
      console.log(error);
    }
  };

  // ─────────────────────────────────────────────────────────────────────────
  // EVENT HANDLER: handleDelete
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Permanently deletes a task from MongoDB via the backend API.
   *
   * FLOW:
   *   1. Send DELETE request to backend
   *   2. On success, filter the deleted task out of local state
   *
   * @param {string} taskId - MongoDB ObjectId of the task to delete
   */
  handleDelete = async (taskId) => {
    try {
      // DELETE {apiUrl}/{taskId} → backend removes from MongoDB
      await deleteTask(taskId);

      // Filter out the deleted task from local state
      // Array.filter() returns a new array (immutable — React best practice)
      const updatedTasks = this.state.tasks.filter(
        (task) => task._id !== taskId
      );
      this.setState({ tasks: updatedTasks });
    } catch (error) {
      console.log(error);
    }
  };
}

export default Tasks;
